settings:
  name: Amazon S3 storage
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"

sidebar:
  entries:
    - title: Amazon S3 storage docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: View your Amazon S3 buckets
          url: /task-viewing-amazon-s3.html
    - title: Manage S3 buckets
      entries:
        - title: Add S3 buckets
          url: /task-add-s3-bucket.html
        - title: Change S3 bucket settings
          url: /task-change-s3-bucket-settings.html
        - title: Use NetApp data services with S3 buckets
          url: /task-s3-enable-data-services.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Storage Management
  repo: storage-management-family
  